title: "Juggle App Privacy Policies"
description: "Privacy policies for apps developed by Hello Juggler LLC"
author: "Hello Juggler LLC"
email: "contact@hellojuggler.com"
theme: minima
markdown: kramdown
header_pages:
  - index.md
